### ISSUE TITLE
Apacheのルートフォルダが変わらない

### ISSUE THREAD

**Issue by hibikine** [Mushus/php-docker-example#2]
```.env
# version
MYSQL_VERSION=8.0.3
REDIS_VERSION=3.2.11
PHP_VERSION=7.2.1

# RDBのデータディレクトリ
RDB_DIR=./rdb_data

# RDBのルートパスワード
RDB_ROOT_PASSWORD=password

# 接続ユーザーの設定
# RDBユーザー名
RDB_USER=card
# RDBパスワード
RDB_PASSWORD=password

# RDBのポート
RDB_PORT=3306

# apacheのルートフォルダ
APACHE_DOCUMENT_ROOT=/var/www/http/public/

# /var/www/httpに配置するプロジェクトフォルダ
WEBRBOOT=./

# アプリケーションポート
HTTP_PORT=80

# KVSのポート
KVS_PORT=6379
```

と設定してもApacheのルートフォルダがpublicに変わりません。

現在原因を調べていますが、もしかしたら、 https://github.com/docker-library/docs/tree/master/php#user-content-changing-documentroot の設定が必要かもしれません。

**Comment by Mushus** [comment]
dotenvファイルの内容をコンテナ側に渡してないからではなくて？

**Comment by Mushus** [comment]
あとから試してみる

**Comment by Mushus** [comment]
初期状態だとAPACHE_DOCUMENT_ROOTは使えない模様。
ビルド時に変更できるようにした。

https://github.com/Mushus/php-docker-example/commit/19a0ca785a9e9f9d91b89aee679a71a4fe62dd3d
